# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a79ec28bc0856856b50462ed0d23c1a1b1f51c1b8d61b072f34d05fdac5c234700e52d119ad37646aada7429a0b089282f41239d9e08005f280ec36437324e6a

test:
  secret_key_base: 983d62c42bc6df99bfd754e75e2632da52a3c0dc3b5d902ae5b5800172811664521a1f073e0664fd25e443c350f9dd7c246d3d024a82fb1f476ff8b8afe3ebb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
